### ISSUE TITLE
Create a log after the OTA process to verify if it was completed successfully

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/vscode-extension#2]
Create a log after the OTA process to verify if it was completed successfully (eg generate a .TXT file; Or process messages in VS Code’s Serial Monitor). Justification: The OTA process takes time to complete (eg: In the updates I made using a GSM connection, the OTA completed after 15 minutes) and at the end of the process, no persistent warning is generated that allows the user to verify that everything went well(Or identify errors during the OTA). (Note: The current pop-up in VS CODE, which informs you of the success of the update, quickly disappears after the OTA is completed)

**Comment by georgevbsantiago** [comment]
Something week to platform functionality: `monitor_filters = log2file`
See: https://docs.platformio.org/en/latest/projectconf/sections/env/options/monitor/monitor_filters.html

**Comment by alvarolb** [comment]
Fixed on version 1.1.0! 

https://github.com/thinger-io/vscode-extension/releases/tag/1.1.0
